env:
  browser: true
  es6: true
extends: airbnb
parserOptions:
  sourceType: module
globals:
  _: true
  $: true
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: 0
